-- Explore All Objects in the DataBase.
Select * 
from INFORMATION_SCHEMA.TABLES

-- Explore all Columns in the DataBase
Select * 
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='dim_customers'

-- Explore all Countries where customers are from
select distinct country 
from gold.dim_customers

-- Explore product categories , syb-categories and products
select distinct category,subcategory,product_name 
from gold.dim_products
order by 1,2,3

-- Exploring Genders 
select distinct gender 
from gold.dim_customers

/*
-- Finding the date of the first and last order
-- Finding the date range in years and months
*/
select 
	min(order_date) first_order_date ,
	max(order_date) last_order_date ,
	datediff(year,min(order_date),max(order_date)) date_range_years,
	datediff(month,min(order_date),max(order_date)) date_range_month
from gold.fact_sales

-- Finding the oldest and youngest customer ages.
select 
	min(birthdate) oldest_DOB ,
	max(birthdate) youngest_DOB ,
	datediff(year,min(birthdate),getdate()) oldest_age,
	datediff(year,max(birthdate),getdate()) youngest_age
from gold.dim_customers

-- Finding Total Sales
select sum(sales_amount) total_sales 
from gold.fact_sales

-- Finding the total items sold
select sum(quantity) total_quantity_sold
from gold.fact_sales

-- Finding the average selling price
select avg(price) avg_selling_price
from gold.fact_sales

-- Finding the total number of orders 
select count(distinct(order_number)) total_orders 
from gold.fact_sales

-- Finding the total number of products
select count(product_key) total_product_sold 
from gold.fact_sales

select count(distinct(product_key)) total_no_of_unique_products
from gold.dim_products

-- Finding the total number of customers
select count(customer_key) total_customers 
from gold.dim_customers

-- Finding the total number of customers who placed an order
select count(distinct customer_key) total_customers 
from gold.fact_sales

-- generating a report that contains the all key metrics
select 'Total Sales' as measure_name , sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity',sum(quantity) from gold.fact_sales
union all
select 'AVG Selling Price',avg(price) from gold.fact_sales
union all
select 'Total No.of Orders',count(distinct(order_number)) total_orders from gold.fact_sales
union all
select 'Total No.of Products sold',count(product_key) total_product_sold 
from gold.fact_sales
union all 
select 'Unique Products',count(distinct(product_key)) total_no_of_unique_products
from gold.dim_products
union all
select 'Total No.of Customers',count(customer_key) total_customers 
from gold.dim_customers

-- Finding the Total No Of customers per country
select country, COUNT(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Total customers by gender
select gender, COUNT(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- total products by category
select category , count(product_key) as total_products
from gold.dim_products
group  by category
order by total_products desc

-- average cost in each category
select category , avg(cost) as average_cost
from gold.dim_products
group  by category
order by average_cost desc

-- revenue generated by each category
select 
	p.category,
	isnull(sum(f.sales_amount),0) as total_revenue 
from gold.fact_sales f
right join gold.dim_products p on f.product_key=p.product_key
group by p.category
order by total_revenue desc

-- revenue generated by each customer 
select 
	c.customer_key ,
	c.first_name,c.last_name ,
	sum(f.sales_amount) as total_revenue 
from gold.fact_sales f
right join gold.dim_customers c on f.customer_key=c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

-- Products sold per country
select 
	c.country,
	SUM(f.quantity) as total_products_sold 
from gold.fact_sales f
right join gold.dim_customers c on f.customer_key=c.customer_key
group by c.country 
order by total_products_sold desc 

-- top 5 products acc. to revenue
select top 5 
	p.product_name,
	SUM(f.sales_amount) as total_revenue 
from gold.fact_sales f
right join gold.dim_products p on p.product_key=f.product_key
group by p.product_name 
order by total_revenue desc

-- bottom 5 products acc. to revenue
select top 5 
	p.product_name,
	SUM(f.sales_amount) as total_revenue 
from gold.fact_sales f
join gold.dim_products p on p.product_key=f.product_key
group by p.product_name 
order by total_revenue 

-- Top 10 revenue generating customers
select 
	t.first_name+' '+t.last_name as customer_name ,
	t. total_revenue 
from (
		select 
			c.customer_key ,
			c.first_name,c.last_name ,
			sum(f.sales_amount) as total_revenue,
			dense_rank()over(order by sum(f.sales_amount) desc) as rank_ 
		from gold.fact_sales f
		right join gold.dim_customers c on f.customer_key=c.customer_key
		group by c.customer_key,c.first_name,c.last_name
	 ) t
where t.rank_<=10

-- Finding the no of customers that are placing certain no of orders.
select 
	t.orders_placed, 
	count(t.customer_key) as total_customers
from (
		select 
			customer_key ,
			count(distinct order_number) as orders_placed 
		from gold.fact_sales
		group by customer_key 
	 ) t
group by t.orders_placed
order by t.orders_placed desc












